# local DAG nodes 4 nodes + 1 monitor
services:
  strix_local_node_a:
    image: postgres:15
    environment:
      POSTGRES_USER: strix_local_node_a
      POSTGRES_PASSWORD: strix
      POSTGRES_DB: strix_node_DB_A
    ports: ["5443:5432"]
    volumes:
      - strix_local_data_node_a:/var/lib/postgresql/data
      - ./db/local_node_schema.sql:/docker-entrypoint-initdb.d/node_schema.sql:ro

  strix_local_node_b:
    image: postgres:15
    environment:
      POSTGRES_USER: strix_local_node_b
      POSTGRES_PASSWORD: strix
      POSTGRES_DB: strix_node_DB_B
    ports: ["5444:5432"]
    volumes:
      - strix_local_data_node_b:/var/lib/postgresql/data
      - ./db/local_node_schema.sql:/docker-entrypoint-initdb.d/node_schema.sql:ro

  strix_local_node_c:
    image: postgres:15
    environment:
      POSTGRES_USER: strix_local_node_c
      POSTGRES_PASSWORD: strix
      POSTGRES_DB: strix_node_DB_C
    ports: ["5445:5432"]
    volumes:
      - strix_local_data_node_c:/var/lib/postgresql/data
      - ./db/local_node_schema.sql:/docker-entrypoint-initdb.d/node_schema.sql:ro

  strix_local_node_d:
    image: postgres:15
    environment:
      POSTGRES_USER: strix_local_node_d
      POSTGRES_PASSWORD: strix
      POSTGRES_DB: strix_node_DB_D
    ports: ["5446:5432"]
    volumes:
      - strix_local_data_node_d:/var/lib/postgresql/data
      - ./db/local_node_schema.sql:/docker-entrypoint-initdb.d/node_schema.sql:ro

  strix_local_monitor_node:
    image: postgres:15
    environment:
      POSTGRES_USER: frontend_orchestration_monitor
      POSTGRES_PASSWORD: strix
      POSTGRES_DB: status_output
    ports: ["5447:5432"]
    volumes:
      - strix_local_data_monitor:/var/lib/postgresql/data
      - ./db/monitor_schema.sql:/docker-entrypoint-initdb.d/monitor_schema.sql:ro

  # Backend services (Go-based nodes + monitor)
  strix_local_backend_a:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGET: node
    image: strix_local_backend_a:latest
    environment:
      MONITOR_URL: http://strix_local_backend_monitor_node:8094
      NODE_ID: node1
      DATABASE_URL: postgres://strix_local_node_a:strix@strix_local_node_a:5432/strix_node_DB_A?sslmode=disable
      DAG_TYPE: local
      PORT: "8090"
      FAKE_TPM_MASTER_KEY: secret-passcode
      FAKE_TPM_STORAGE: /data/tpm
      PEERS: http://node2:8080,http://node3:8080,http://node4:8080
    depends_on:
      - strix_local_node_a
    ports:
      - "8090:8080"

  strix_local_backend_b:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGET: node
    image: strix_local_backend_b:latest
    environment:
      MONITOR_URL: http://strix_local_backend_monitor_node:8094
      NODE_ID: node2
      DATABASE_URL: postgres://strix_local_node_b:strix@strix_local_node_b:5432/strix_node_DB_B?sslmode=disable
      DAG_TYPE: local
      PORT: "8091"
      FAKE_TPM_MASTER_KEY: secret-passcode
      FAKE_TPM_STORAGE: /data/tpm
      PEERS: http://node1:8080,http://node3:8080,http://node4:8080
    depends_on:
      - strix_local_node_b
    ports:
      - "8091:8080"

  strix_local_backend_c:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGET: node
    image: strix_local_backend_c:latest
    environment:
      MONITOR_URL: http://strix_local_backend_monitor_node:8094
      NODE_ID: node3
      DATABASE_URL: postgres://strix_local_node_c:strix@strix_local_node_c:5432/strix_node_DB_C?sslmode=disable
      DAG_TYPE: local
      PORT: "8092"
      FAKE_TPM_MASTER_KEY: secret-passcode
      FAKE_TPM_STORAGE: /data/tpm
      PEERS: http://node1:8080,http://node2:8080,http://node4:8080
    depends_on:
      - strix_local_node_c
    ports:
      - "8092:8080"

  strix_local_backend_d:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGET: node
    image: strix_local_backend_d:latest
    environment:
      MONITOR_URL: http://strix_local_backend_monitor_node:8094
      NODE_ID: node4
      DATABASE_URL: postgres://strix_local_node_d:strix@strix_local_node_d:5432/strix_node_DB_D?sslmode=disable
      DAG_TYPE: local
      PORT: "8093"
      FAKE_TPM_MASTER_KEY: secret-passcode
      FAKE_TPM_STORAGE: /data/tpm
      PEERS: http://node1:8080,http://node2:8080,http://node3:8080
    depends_on:
      - strix_local_node_d
    ports:
      - "8093:8080"
    
  strix_local_backend_monitor_node:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TARGET: monitor
    image: strix_local_monitor:latest
    environment:
      NODE_ID: monitor
      DATABASE_URL: postgres://frontend_orchestration_monitor:strix@strix_local_monitor_node:5432/status_output?sslmode=disable
      PORT: "8094"
      FAKE_TPM_MASTER_KEY: secret-passcode
      FAKE_TPM_STORAGE: /data/tpm
      MONITOR_ONLY: "true"
    depends_on:
      - strix_local_monitor_node
    ports:
      - "8094:8080"

volumes:
  strix_local_data_node_a:
  strix_local_data_node_b:
  strix_local_data_node_c:
  strix_local_data_node_d:
  strix_local_data_monitor:
